* 1692 bug inputtext should not be using textlabelcontrol colours
Krypton-Suite/Standard-Toolkit pull request #1733
Opened 2024-08-18 10:02 UTC by Wagnerp

* Resolves #1692 + a few alterations

![image](https://github.com/user-attachments/assets/b5d714c8-c3b3-4161-8d48-d3811689fd97)

2024-08-18 11:16 UTC, giduac requested changes
The  introduction of `GlobalStaticMethods` and subsequent changes are not part of this bug and should be handled through a FR.

2024-08-18 11:22 UTC, Wagnerp commented
> The introduction of `GlobalStaticMethods` and subsequent changes are not part of this bug and should be handled through a FR.

No, as a bool method is introduced in this class that detects _if_ a black theme is being used. See Source/Krypton Components/Krypton.Toolkit/Controls Visuals/VisualMessageBoxFormDep.cs, line 166 for usage.

2024-08-18 11:56 UTC, giduac commented
> > The introduction of `GlobalStaticMethods` and subsequent changes are not part of this bug and should be handled through a FR.
> 
> No, as a bool method is introduced in this class that detects _if_ a black theme is being used. See Source/Krypton Components/Krypton.Toolkit/Controls Visuals/VisualMessageBoxFormDep.cs, line 166 for usage.

One simple method is added.
And moving those to a new class is creates a massive change  which is outside the scope of this ticket.

I disagree with those changes.

2024-08-18 11:57 UTC, giduac commented
Running: testform/Messagebox test click the top button: creates an error and crashes the program.

2024-08-18 12:38 UTC, Wagnerp commented
> > > The introduction of `GlobalStaticMethods` and subsequent changes are not part of this bug and should be handled through a FR.
> > 
> > 
> > No, as a bool method is introduced in this class that detects _if_ a black theme is being used. See Source/Krypton Components/Krypton.Toolkit/Controls Visuals/VisualMessageBoxFormDep.cs, line 166 for usage.
> 
> One simple method is added. And moving those to a new class is creates a massive change which is outside the scope of this ticket.
> 
> I disagree with those changes.

@giduac 

The 'bigger' changes have been rolled back for a future FR, **but** `IsUsingDefaultBlackThemes()` still remains to avoid code duplication.

2024-08-18 16:51 UTC, Wagnerp commented
> Running: testform/Messagebox test click the top button: creates an error and crashes the program.

Hi @giduac 

I don't know why, but it's triggering a error in the `PaletteWrapLabel` class?

2024-08-18 16:54 UTC, Wagnerp commented
?

![image](https://github.com/user-attachments/assets/e1e3e230-ffbf-4d2e-8066-462ed6256f1c)

2024-08-19 04:57 UTC, giduac commented on Source/Krypton Components/Krypton.Toolkit/Controls Visuals/VisualAboutBoxForm.Designer.cs
>          /// </summary>
How is the aboutbox related to #1692?

2024-08-19 05:04 UTC, giduac commented
Imo this change needs a closer look and there are to many things going on here to just change the text color.
A more simple alteration should be possible to solve this.

2024-08-19 11:58 UTC, giduac commented
@Wagnerp 

I have a simple fix for this problem.
As soon as Alpha builds inside VS again I will push the branch for testing.

2024-08-19 16:33 UTC, giduac commented
@Wagnerp 
I've tested the simple change and it works fine.
So imo this PR can be Closed.

New PR underway.

2024-08-19 17:10 UTC, closed without merging